name: ci

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Angular build cache
        uses: actions/cache@v4
        with:
          path: .angular/cache
          key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-angular-

      - name: Install dependencies
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Unit tests (library)
        if: ${{ hashFiles('projects/ngxsmk-tel-input/**/*.spec.ts') != '' }}
        env:
          CHROME_BIN: /usr/bin/google-chrome
          CI: true
        run: npx ng test ngxsmk-tel-input --watch=false --browsers=ChromeHeadless --progress=false

      - name: Build library
        run: npx ng build ngxsmk-tel-input --configuration production

      - name: Build demo (optional)
        if: ${{ hashFiles('projects/demo/src/main.ts') != '' }}
        run: npx ng build demo --configuration production

      - name: Pack npm tarball
        working-directory: dist/ngxsmk-tel-input
        run: npm pack

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ngxsmk-tel-input
          path: |
            dist/ngxsmk-tel-input/**
            dist/ngxsmk-tel-input/*.tgz
